### ISSUE TITLE
homebrige-hc-sr501 always triggered 

### ISSUE THREAD

**Issue by c13m0n5t3r** [lucavb/homebridge-hc-sr501#5] opened 2017-08-31 05:33 UTC
Hey, i use this Plugin and have problems.
The motion sensor don’t toggle between heigh and low so the info in HomeKit is not correct.
I show you some pictures and I hope somebody can help.
![Image](http://i.imgur.com/y0Qk3Jx.jpg)
![Image](http://i.imgur.com/1ERUFJT.jpg)
I can’t find the problems

Thank you!

**Comment by lucavb** [comment] 2017-09-06 07:47
duplicate of the comments in https://github.com/lucavb/homebridge-hc-sr501/issues/3

**Closed by lucavb** 2017-09-06 07:47 UTC
